#!/usr/bin/env bash
#
# Create the git-ignored backend/.env for a real Supabase project.
#
# The password is read from the terminal with echo disabled and is never passed
# as a command argument, so it does not appear in shell history, in `ps` output,
# or anywhere on screen. It is percent-encoded before being placed in the URL,
# because a generated password may legitimately contain characters that would
# otherwise terminate or corrupt the connection string.
#
# Usage:
#   backend/scripts/setup-local-env.sh <project-ref> [db-role]
#
# Examples:
#   backend/scripts/setup-local-env.sh yygdxhglxaeozpcllauy          # bootstrap, as postgres
#   backend/scripts/setup-local-env.sh yygdxhglxaeozpcllauy app_api  # least privilege
set -euo pipefail

PROJECT_REF="${1:-}"
DB_ROLE="${2:-postgres}"
POOLER_HOST="${POOLER_HOST:-aws-0-us-east-1.pooler.supabase.com}"
POOLER_PORT=5432   # session mode. NEVER 6543 — see docs/operations/supabase-bootstrap.md

if [ -z "$PROJECT_REF" ]; then
  echo "usage: $0 <project-ref> [db-role]" >&2
  exit 64
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$BACKEND_DIR/.env"

# Refuse to write anywhere git would track.
if ! git -C "$BACKEND_DIR" check-ignore -q "$ENV_FILE" 2>/dev/null; then
  echo "REFUSING: $ENV_FILE is not git-ignored. Fix .gitignore before continuing." >&2
  exit 1
fi

if [ -e "$ENV_FILE" ]; then
  printf 'backend/.env already exists. Overwrite? [y/N] '
  read -r reply
  case "$reply" in
    y | Y) : ;;
    *) echo "aborted; nothing changed"; exit 0 ;;
  esac
fi

command -v node >/dev/null 2>&1 || { echo "node is required (v22+)" >&2; exit 1; }

# Read the password with the terminal echo turned off, restoring it even if the
# script is interrupted.
DB_PASSWORD=''
if [ -t 0 ]; then
  printf 'Supabase database password for role "%s" (input hidden): ' "$DB_ROLE"
  stty_state="$(stty -g)"
  trap 'stty "$stty_state" 2>/dev/null || true' EXIT INT TERM
  stty -echo
  IFS= read -r DB_PASSWORD || true
  stty "$stty_state"
  trap - EXIT INT TERM
  printf '\n'
else
  # Non-interactive (tests). Still never an argument.
  IFS= read -r DB_PASSWORD || true
fi

if [ -z "$DB_PASSWORD" ]; then
  echo "no password entered; nothing written" >&2
  exit 1
fi

# Percent-encode. The password reaches node on stdin, never in argv or the
# environment, so it is not visible to other processes.
ENCODED="$(printf '%s' "$DB_PASSWORD" | node -e '
  let data = ""
  process.stdin.setEncoding("utf8")
  process.stdin.on("data", (chunk) => { data += chunk })
  process.stdin.on("end", () => { process.stdout.write(encodeURIComponent(data)) })
')"
DB_PASSWORD=''
unset DB_PASSWORD

umask 077
cat > "$ENV_FILE" <<ENVFILE
# Generated by backend/scripts/setup-local-env.sh — git-ignored, never commit.
# Session pooler (port 5432). Transaction mode (6543) is not usable: it loses
# session state between transactions and breaks the Outbox claim pattern.
NODE_ENV=development
LOG_LEVEL=info

DATABASE_URL=postgresql://${DB_ROLE}.${PROJECT_REF}:${ENCODED}@${POOLER_HOST}:${POOLER_PORT}/postgres

SUPABASE_JWT_ISSUER=https://${PROJECT_REF}.supabase.co/auth/v1
SUPABASE_JWKS_URL=https://${PROJECT_REF}.supabase.co/auth/v1/.well-known/jwks.json
SUPABASE_JWT_AUDIENCE=authenticated
ENVFILE
ENCODED=''
unset ENCODED
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (mode 600, git-ignored)"
echo "  role: ${DB_ROLE}.${PROJECT_REF}"
echo "  host: ${POOLER_HOST}:${POOLER_PORT}  (session pooler)"
echo "  password: not shown, not logged, not in shell history"
echo
echo "next: cd backend && npm run migrate"
